services:
  server:
    container_name: faccina-server
    build:
      context: server
    depends_on:
      - db
    ports:
      - '${SERVER_HTTP_PORT}:3000'
    volumes:
      - ./data:/opt/server/data:rw
      - ./logs:/opt/server/logs:rw
      - ./content:/opt/server/content:r
  web:
    container_name: faccina-web
    build:
      context: web
    depends_on:
      - server
    environment:
      CDN_URL: ${CDN_URL}
    ports:
      - '${WEB_HTTP_PORT}:5000'
  db:
    container_name: faccina-db
    image: postgres
    environment:
      POSTGRES_DB: '${DB_NAME:-faccina}'
      POSTGRES_USER: '${DB_USER:-faccina}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-faccina}'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: