services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./config.toml:/app/config.toml:r
      - ./data:/app/data:rw # Directory containing the SQLite file
      - ./content:/content:r
      - ./images:/images:rw
