services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./config.docker.toml:/app/config.toml:r
      - ./content:/content:r
      - ./images:/images:rw
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=faccina
      - POSTGRES_USER=faccina
      - POSTGRES_DB=faccina

volumes:
  postgres_data:
